# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TonghopbieuDockWidget
                                 A QGIS plugin
 Tổng hợp 12 mẫu biểu điều tra rừng theo Thông tư 16
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-06-21
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Nguyễn Văn Thị
        email                : thinguyen.xmg@xuanmaijsc.vn
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
from qgis.PyQt import uic
from PyQt5 import QtWidgets
from PyQt5.QtCore import pyqtSignal
from qgis.core import QgsMapLayerProxyModel
from PyQt5.QtCore import pyqtSignal
from PyQt5.QtWidgets import QDockWidget
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'tong_hop_dockwidget_base.ui'))


class TonghopbieuDockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        super(TonghopbieuDockWidget, self).__init__(parent)
        # Set up the user interface from Designer.
        # After setupUI you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://doc.qt.io/qt-5/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        
    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()
    
    